- name: installed rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv

- name: registerd rbenv path
  template:
    src: 001_rbenv.sh
    dest: ~/.bash.d/001_rbenv.sh
    mode: 0755

- name: installed ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build




- name: configured ruby version {{ __ruby_version }}
  shell: bash -lc "rbenv global {{ __ruby_version }} "
  register: res
  failed_when: res.rc not in [0, 1]

- name: installed ruby "{{ __ruby_version }}"
  shell: bash -lc 'rbenv install "{{ __ruby_version }}" && rbenv global {{ __ruby_version }}  '　
  when: res.rc == 1
